swagger: '2.0'
info: 
 version: ""
 title: Payment
 description: "Payment service spec"
 license: 
  name: MIT
  url: "http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT"
#host: payment
#basePath: "/"
#securityDefinitions: 
#schemes: 
 #- http
basePath: /payment
consumes: 
 - application/json; charset=utf-8
produces: 
 - application/json; charset=utf-8
paths: 
  /health: 
    get: 
      operationId: HealthEndpoint
      parameters: 
      responses: 
        200: 
          description: success
          schema: 
            $ref: '#/definitions/health'
  /paymentAuth: 
    post: 
      operationId: AuthoriseEndpoint
      parameters:
      responses: 
        200: 
          description: ""
          schema: 
            $ref: '#/definitions/paymentAuth'
definitions: 
   health: 
     title: Health
     type: object
     properties: 
       health: 
         type: array
         items: 
           type: object
           properties: 
             service: 
               type: string
             status: 
               type: string
             time: 
               type: string
     required: 
       - health
   paymentAuth: 
     title: paymentAuth response
     type: object
     properties: 
       authorised: 
         type: boolean
     required: 
       - authorised